main: com.kolinkrewinkel.BitLimitNPCs.BitLimitNPCs
name: BitLimitNPCs
version: ${project.version}
author: Kolin Krewinkel
description: Non-playing characters for specific use cases on the BitLimit Private Survival server. Currently only includes item-repairing blacksmiths.
website: https://github.com/kolinkrewinkel/BitLimitNPCs/
commands:
    npc:
        description: Undefined
permissions:
    npc.*:
        description: Gives all permissions of BitLimit Tweaks plugin toggling.
        default: op
depend: [RemoteEntities]