main: com.bitlimit.NPCs.NPCs
name: NPCs
version: ${project.version}
author: Kolin Krewinkel
description: Non-playing characters.
website: https://github.com/BitLimit/NPCs/
commands:
    npc:
        description: Undefined
permissions:
    npc.*:
        description: Gives all permissions of BitLimit Tweaks plugin toggling.
        default: op
depend: [RemoteEntities]